### ISSUE TITLE
RuntimeError: File size unexpectedly exceeded ZIP64 limit in BASELINE

### ISSUE THREAD

**Issue by frj555** [SoccerNet/sn-gamestate#10]
Hi, I found error when runing the baseline by default. It seems ZIP64 limit is exceeded after MMOCR step. 

Traceback (most recent call last):
  File "C:\Users\---\anaconda3\envs\tracklab\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\---\anaconda3\envs\tracklab\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Git\soccernet\tracklab\tracklab\main.py", line 119, in <module>
    main()
  File "C:\Users\---\anaconda3\envs\tracklab\lib\site-packages\hydra\main.py", line 94, in decorated_main
    _run_hydra(
  File "C:\Users\---\anaconda3\envs\tracklab\lib\site-packages\hydra\_internal\utils.py", line 394, in _run_hydra
    _run_app(
  File "C:\Users\---\anaconda3\envs\tracklab\lib\site-packages\hydra\_internal\utils.py", line 457, in _run_app
    run_and_report(
  File "C:\Users\---\anaconda3\envs\tracklab\lib\site-packages\hydra\_internal\utils.py", line 223, in run_and_report
    raise ex
  File "C:\Users\---\anaconda3\envs\tracklab\lib\site-packages\hydra\_internal\utils.py", line 220, in run_and_report
    return func()
  File "C:\Users\---\anaconda3\envs\tracklab\lib\site-packages\hydra\_internal\utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "C:\Users\---\anaconda3\envs\tracklab\lib\site-packages\hydra\_internal\hydra.py", line 132, in run
    _ = ret.return_value
  File "C:\Users\---\anaconda3\envs\tracklab\lib\site-packages\hydra\core\utils.py", line 260, in return_value
    raise self._return_value
  File "C:\Users\---\anaconda3\envs\tracklab\lib\site-packages\hydra\core\utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "C:\Program Files\Git\soccernet\tracklab\tracklab\main.py", line 59, in main
    tracking_engine.track_dataset()
  File "C:\Program Files\Git\soccernet\tracklab\tracklab\engine\engine.py", line 118, in track_dataset
    self.callback(
  File "C:\Users\---\anaconda3\envs\tracklab\lib\site-packages\lightning\fabric\fabric.py", line 892, in call
    method(*args, **kwargs)
  File "C:\Program Files\Git\soccernet\tracklab\tracklab\datastruct\tracker_state.py", line 233, in on_video_loop_end
    self.save()
  File "C:\Program Files\Git\soccernet\tracklab\tracklab\datastruct\tracker_state.py", line 276, in save
    with self.zf["save"].open(f"{self.video_id}.pkl", "w") as fp:
  File "C:\Users\___\anaconda3\envs\tracklab\lib\zipfile.py", line 1172, in close
    raise RuntimeError(
RuntimeError: File size unexpectedly exceeded ZIP64 limit
Tracking videos (SNGS-021) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/1 10:47:05 • 0:00:00[W C:\cb\pytorch_1000000000000\work\torch\csrc\CudaIPCTypes.cpp:95] Producer process tried to deallocate over 1000 memory blocks referred by consumer processes. Deallocation might be significantly slowed down. We assume it will never going to be the case, but if it is, please file but to https://github.com/pytorch/pytorch
[W C:\cb\pytorch_1000000000000\work\torch\csrc\CudaIPCTypes.cpp:15] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]
[W CUDAGuardImpl.h:46] Warning: CUDA warning: driver shutting down (function uncheckedGetDevice)
[W CUDAGuardImpl.h:62] Warning: CUDA warning: invalid device ordinal (function uncheckedSetDevice)
....

**Comment by VlSomers** [comment]
Hi @frj555 , is it fixed now? If yes, could you share what you have done?

**Comment by frj555** [comment]
Hi. I am not 100% sure this issue it is solved but what I did is changing program line in my local drive,  in File "C:\Program Files\Git\soccernet\tracklab\tracklab\datastruct\tracker_state.py", line 276, in save, adding ", force_zip64=True" :

- Original line 276: with self.zf["save"].open(f"{self.video_id}.pkl", "w") as fp: 
- New line 276: with self.zf["save"].open(f"{self.video_id}.pkl", "w", force_zip64=True) as fp:

I will update if this issue appears again. Many thanks.
